# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto

# type: ignore

"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="block.proto",
    package="block",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0b\x62lock.proto\x12\x05\x62lock\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11transaction.proto"\xe3\x01\n\x05\x42lock\x12\x12\n\x05index\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x32\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x12.\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x18.transaction.Transaction\x12\x12\n\x05nonce\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x1a\n\rprevious_hash\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\x08\n\x06_indexB\x0c\n\n_timestampB\x08\n\x06_nonceB\x10\n\x0e_previous_hashb\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,
        transaction__pb2.DESCRIPTOR,
    ],
)


_BLOCK = _descriptor.Descriptor(
    name="Block",
    full_name="block.Block",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="index",
            full_name="block.Block.index",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="timestamp",
            full_name="block.Block.timestamp",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="transactions",
            full_name="block.Block.transactions",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="nonce",
            full_name="block.Block.nonce",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="previous_hash",
            full_name="block.Block.previous_hash",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="_index",
            full_name="block.Block._index",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="_timestamp",
            full_name="block.Block._timestamp",
            index=1,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="_nonce",
            full_name="block.Block._nonce",
            index=2,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="_previous_hash",
            full_name="block.Block._previous_hash",
            index=3,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=75,
    serialized_end=302,
)

_BLOCK.fields_by_name[
    "timestamp"
].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_BLOCK.fields_by_name["transactions"].message_type = transaction__pb2._TRANSACTION
_BLOCK.oneofs_by_name["_index"].fields.append(_BLOCK.fields_by_name["index"])
_BLOCK.fields_by_name["index"].containing_oneof = _BLOCK.oneofs_by_name["_index"]
_BLOCK.oneofs_by_name["_timestamp"].fields.append(_BLOCK.fields_by_name["timestamp"])
_BLOCK.fields_by_name["timestamp"].containing_oneof = _BLOCK.oneofs_by_name[
    "_timestamp"
]
_BLOCK.oneofs_by_name["_nonce"].fields.append(_BLOCK.fields_by_name["nonce"])
_BLOCK.fields_by_name["nonce"].containing_oneof = _BLOCK.oneofs_by_name["_nonce"]
_BLOCK.oneofs_by_name["_previous_hash"].fields.append(
    _BLOCK.fields_by_name["previous_hash"]
)
_BLOCK.fields_by_name["previous_hash"].containing_oneof = _BLOCK.oneofs_by_name[
    "_previous_hash"
]
DESCRIPTOR.message_types_by_name["Block"] = _BLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Block = _reflection.GeneratedProtocolMessageType(
    "Block",
    (_message.Message,),
    {
        "DESCRIPTOR": _BLOCK,
        "__module__": "block_pb2"
        # @@protoc_insertion_point(class_scope:block.Block)
    },
)
_sym_db.RegisterMessage(Block)


# @@protoc_insertion_point(module_scope)
