# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
# type: ignore
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="transaction.proto",
    package="transaction",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x11transaction.proto\x12\x0btransaction"\x99\x01\n\x0bTransaction\x12\x13\n\x06sender\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\trecipient\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x61mount\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x16\n\tsignature\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\t\n\x07_senderB\x0c\n\n_recipientB\t\n\x07_amountB\x0c\n\n_signatureb\x06proto3',
)


_TRANSACTION = _descriptor.Descriptor(
    name="Transaction",
    full_name="transaction.Transaction",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="sender",
            full_name="transaction.Transaction.sender",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="recipient",
            full_name="transaction.Transaction.recipient",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="amount",
            full_name="transaction.Transaction.amount",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="signature",
            full_name="transaction.Transaction.signature",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="_sender",
            full_name="transaction.Transaction._sender",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="_recipient",
            full_name="transaction.Transaction._recipient",
            index=1,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="_amount",
            full_name="transaction.Transaction._amount",
            index=2,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="_signature",
            full_name="transaction.Transaction._signature",
            index=3,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=35,
    serialized_end=188,
)

_TRANSACTION.oneofs_by_name["_sender"].fields.append(
    _TRANSACTION.fields_by_name["sender"]
)
_TRANSACTION.fields_by_name["sender"].containing_oneof = _TRANSACTION.oneofs_by_name[
    "_sender"
]
_TRANSACTION.oneofs_by_name["_recipient"].fields.append(
    _TRANSACTION.fields_by_name["recipient"]
)
_TRANSACTION.fields_by_name["recipient"].containing_oneof = _TRANSACTION.oneofs_by_name[
    "_recipient"
]
_TRANSACTION.oneofs_by_name["_amount"].fields.append(
    _TRANSACTION.fields_by_name["amount"]
)
_TRANSACTION.fields_by_name["amount"].containing_oneof = _TRANSACTION.oneofs_by_name[
    "_amount"
]
_TRANSACTION.oneofs_by_name["_signature"].fields.append(
    _TRANSACTION.fields_by_name["signature"]
)
_TRANSACTION.fields_by_name["signature"].containing_oneof = _TRANSACTION.oneofs_by_name[
    "_signature"
]
DESCRIPTOR.message_types_by_name["Transaction"] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transaction = _reflection.GeneratedProtocolMessageType(
    "Transaction",
    (_message.Message,),
    {
        "DESCRIPTOR": _TRANSACTION,
        "__module__": "transaction_pb2"
        # @@protoc_insertion_point(class_scope:transaction.Transaction)
    },
)
_sym_db.RegisterMessage(Transaction)


# @@protoc_insertion_point(module_scope)
